name:                carrier
version:             0.1.0.0
github:              "genya0407/carrier"
license:             BSD3
author:              "Yusuke Sangenya"
maintainer:          "longinus.eva@gmail.com"
copyright:           "2021 Yusuke Sangenya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/genya0407/carrier#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- containers
- optparse-applicative
- aeson-pretty
- bytestring
- system-fileio
- system-filepath
- process
- bifunctor
- tostring
- neat-interpolation

library:
  source-dirs: src
  default-extensions:
    - DeriveGeneric
    - OverloadedStrings
    - ScopedTypeVariables
    - QuasiQuotes

executables:
  carrier:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carrier

tests:
  carrier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carrier
